Always good to tell users what depenedencies they need to run your code!
However, the project still doesn't work for me- I get this:

$ python lines.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1413, in __call__
    return self.func(*args)
  File "lines.py", line 522, in start
    GAME(game_root,game)
  File "lines.py", line 552, in __init__
    button_dict['button'].configure(bg=colour.get(),command = partial(self.cross_line,button_dict))
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1205, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1196, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: unknown color name "SystemButtonFace"